export enum Role {
    User = 'User',
    Admin = 'ADMIN',
    Enterpreneur = 'ENTREPRENEUR',
    TIHCL_MANAGER = 'MANEGER',
    TIHCL_EXECUTOR = 'EXECUTIVE-MANAGER',
    AGENCY_MANAGER = 'AGENCY_MANAGER',
    AGENCY_EXECUTOR = 'AGENCY_EXECUTOR',
    CALL_CENTER = 'CALL_CENTER',
    DEPARTMENT = 'DEPARTMENT',
    SPIU = 'SPIU',
    AGENCY_USER = "AGENCY_USER"
}