export enum Role {
    User = 'User',
    Admin = 'ADMIN',
    AGENCY_MANAGER = 'AGENCY_MANAGER',
    AGENCY_EXECUTOR = 'AGENCY_EXECUTOR',
    CALL_CENTER = 'CALL_CENTER',
    DEPARTMENT = 'DEPARTMENT',
    SPIU = 'SPIU',
    AGENCY_USER = "AGENCY_USER",
    DEVELOPER = "DEVELOPER",
    FINANCE = "FINANCE",
    DIC = "DIC",
    DATA_ENTRY = "DATA_ENTRY",
    SERP="SERP",
    MEPMA="MEPMA"
}