import { get } from "jquery";
import { environment } from "src/environments/environment";

export const API_BASE_URL = environment.apiUrl;
export const APIS = {
    programCreation:{
        addprogram: API_BASE_URL + '/program/create',
        addSessions: API_BASE_URL + '/program/session/create',
        editSession: API_BASE_URL + '/program/session/update',
        addLocation: API_BASE_URL + '/location/save',
        getLocation: API_BASE_URL + '/agency/locations/',
        getProgramType: API_BASE_URL + '/program/types/agency/id/',
        getLocationByAgency: API_BASE_URL + '/agency/locationdetails',
        getResource: API_BASE_URL + '/agency/resources',
        getAllResource: API_BASE_URL + '/agency/resources/dropdown',
        addResource: API_BASE_URL + '/resource/save',
        getProgramsList: API_BASE_URL + '/programs',
        getProgramsListByAgency: API_BASE_URL + '/agency/programs/dropdown/',
        getIncompletProgramsListByAgency: API_BASE_URL + '/programs/with-participants/',
        getNewProgramListByAgency: API_BASE_URL + '/programs/status/status-list/',
        getProgramsListByAgencyStatus: API_BASE_URL + '/programs/status',
        getProgramsListByAgencyDetails: API_BASE_URL + '/agency/programs/',
        getProgramsListByAgencyByStatusDetails: API_BASE_URL + '/agency/programs/by/status/',
        getSingleProgramsList: API_BASE_URL + '/program/',
        getActivityList: API_BASE_URL + '/activities',
        getActivityListbyId: API_BASE_URL + '/activity/agency/',
        getSubActivityListByActivity: API_BASE_URL + '/activityById',
        getESDPProgram: API_BASE_URL + '/getESDPTraining',
        addESDPProgram: API_BASE_URL + '/SaveESDPTraining',
        updateProgram: API_BASE_URL + '/updateProgram',
        deleteSession: API_BASE_URL + '/program/session/delete',
        deleteProgram: API_BASE_URL + '/program/delete/',
        getProgramsListBySession: API_BASE_URL + '/programs/status/',
        updateSessionByStatus: API_BASE_URL + '/programs/status/',
        programSummary: API_BASE_URL + '/programs/status/summary/',
        sessionFilesDelete: API_BASE_URL + '/program-session-files/', 
        uploadProgram: API_BASE_URL + '/program/import', 
        downloadProgramsDataPdf: API_BASE_URL + '/program/pdf/',
        downloadProgramsDataExcel: API_BASE_URL + '/program-details/excel/',
        downloadResourceData: API_BASE_URL + '/resource/excel/',
        downloadSessionsData: API_BASE_URL + '/program/session/pdf/',
        downloadProgramSummaryPdf: API_BASE_URL + '/program/summary/pdf/',
        downloadProgramSummaryExcel: API_BASE_URL + '/program/summery/excel/',
        downloadProgramExpenditureExcel: API_BASE_URL + '/export-program-expenditure',
        downloadCombinedExpenditureExcel: API_BASE_URL + '/combined/expenditure/excel/',
        downloadProgramOverviewReportExcel: API_BASE_URL + '/programs-status/',
        downloadProgramParticipantStatusExcel: API_BASE_URL + '/programs-participant-status/',
        downloadProgramParticipantStatusPdf: API_BASE_URL + '/programs-participant-status/pdf/',
        downloadProgramMonitoringReportPdf: API_BASE_URL + '/program-monitoring-report/pdf/',
        updateOverDue: API_BASE_URL + '/',
        getProgramsListByDistrictDetails: API_BASE_URL + '/agency/programs/district/',
        resheduleData: API_BASE_URL + '/program-reschedule-data/',
    },
    resheduleProgram:{
        getResheduleData: API_BASE_URL + '/program-reschedule-data/programs/',

    },
    physicalTagets:{
        getTargets: API_BASE_URL + '/targets/physical/agency/',
        saveTargets: API_BASE_URL + '/targets/physical/save',
        updateTargets: API_BASE_URL + '/targets/physical/update/',
        deleteTargets: API_BASE_URL + '/targets/physical/',
        getTargetById: API_BASE_URL + '/targets/physical/',
    },
    FinancialTagets:{
        getTargets: API_BASE_URL + '/api/outcome-targets?',
        saveTargets: API_BASE_URL + '/targets/physical/save',
        updateTargets: API_BASE_URL + '/targets/physical/update/',
        deleteTargets: API_BASE_URL + '/targets/physical/',
        getTargetById: API_BASE_URL + '/targets/physical/',
    },
    nonparticipant:{
         add: API_BASE_URL + '/influenced-participants/save',
         update: API_BASE_URL + '/influenced-participants/',
         delete: API_BASE_URL + '/influenced-participants/',

    },

    participantdata:{
        add: API_BASE_URL + '/participant/save',
        update: API_BASE_URL + '/updateParticipant',
        getDataByProgramId: API_BASE_URL + '/program/participants/dropdown/',
        getDataByProgramBYDeatisl: API_BASE_URL + '/program/participants/',
        getDataUploadedByProgramBYDeatisl: API_BASE_URL + '/participants/temp/',
        saveOrgnization: API_BASE_URL + '/organization/save',
        getOrgnizationData: API_BASE_URL + '/organization/list',
        getOrgnizationDataOnlyId: API_BASE_URL + '/organization-names',
        getParticipantList: API_BASE_URL + '/participants',
        getParticipantListByAgency: API_BASE_URL + '/agency/participants/',
        getParticipantDetailsById: API_BASE_URL + '/getParticipantById/',
        uploadParticipant: API_BASE_URL + '/upload',
        uploadParticipantData: API_BASE_URL + '/participants/import',
        downloadParticipantDataPdf: API_BASE_URL + '/program/participant/pdf/',
        
        downloadParticipantDataExcel: API_BASE_URL + '/participant-details/excel/',
        downloadParticipantAgencyDataPdf: API_BASE_URL + '/programs-participant-status/pdf/',
        downloadParticipantAgencyDataEXcel: API_BASE_URL + '/programs-participant-status/',
        downloadParticipantTempData: API_BASE_URL + '/ParticipantTemp/excel/sheets/',
        migrateApi: API_BASE_URL + '/participants/temp/migrate',
        deleteTempParticipant: API_BASE_URL + '/participants/temp/',
        updateTempParticipant: API_BASE_URL + '/participants/temp/',
    },
    counsellerData:{
        add: API_BASE_URL + '/saveCounsellor',
        getData: API_BASE_URL + '/getAllCounsellors',
    },
    userRegistration:{
        add: API_BASE_URL + '/auth/register',
        addAgent: API_BASE_URL + '/auth/register',
        editProfile: API_BASE_URL + '/login/user/update',
        getUserById: API_BASE_URL + '/login/user',        
    },
    masterList: {
        changePassword:API_BASE_URL+'/login/change-password',
        agencyList: API_BASE_URL + '/agencies',
        getUserBasedOnAgency:API_BASE_URL+'/new/program/monitoring-dropdown/',
        locationList: API_BASE_URL + '/locations',
        locationDetailsById: API_BASE_URL + '/agency/locationdetails/',
        getUserList: API_BASE_URL + '/login/allusrs',
        getresources: API_BASE_URL + '/resources',
        getResourceDetailsById: API_BASE_URL + '/agency/resources',
        getDistricts: API_BASE_URL + '/getAllDistricts',
        getSectors: API_BASE_URL + '/getallsectors',
        getMandal: API_BASE_URL + '/getAllmandalsOfDistrictsById/',
        getMandalName: API_BASE_URL + '/getAllmandalsOfDistrictsByName/',
        resourceDownload: API_BASE_URL + '/resource/excel/',
        locationDownload: API_BASE_URL + '/location/excel/',
        organizationDownload: API_BASE_URL + '/organization/excel',
        updateLocationStatus: API_BASE_URL + '/locations/update/',
        deleteLocation: API_BASE_URL + '/locations/delete/',
        updateResourceStatus: API_BASE_URL + '/resource/update/',
        deleteResource: API_BASE_URL + '/resource/delete/',
        getOrgnizationDetailsById: API_BASE_URL + '/organization/list',
    },
    trainingtargets:{
        getTrainingtargets: API_BASE_URL + '/targets/financial/year/summary',

    },
    nontrainingtargets:{
        getBudgetHeadList: API_BASE_URL + '/progress/monitoring/get/activities/',
        getSubActivityList: API_BASE_URL + '/non-training/getAll/subActivities/',
        getResourceList: API_BASE_URL + '/non-training/resources/non-training-activity?nonTrainingActivityId=',
        getSelectedOrganization: API_BASE_URL + '/selected-organizations',
        getTravelList: API_BASE_URL + '/api/travel/',
        updateTarets: API_BASE_URL + '/progress/monitoring/non-training-achievement/',
        getNonTrainingtargets: API_BASE_URL + '/progress/monitoring/non-training/physical/financial/',
        saveNonTrainingtargetsAleapPriliminary: API_BASE_URL + '/non-training',
        saveNonTrainingtargetsCodeIT: API_BASE_URL + '/non-training/save',
        updateNonTrainingtargetsAleapPriliminary: API_BASE_URL + '/non-training/update/',
        deleteNonTrainingtargetsAleapPriliminary: API_BASE_URL + '/non-training/delete/',
        getNonTrainingtargetsAleapPriliminaryById: API_BASE_URL + '/non-training/all/expenditures?nonTrainingActivityId=',
        getNonTrainingtargetsAleapContingencyId: API_BASE_URL + '/non-training/all/resources?nonTrainingActivityId=',
        saveNonTrainingtargetsAleapContingency: API_BASE_URL + '/non-training/resource',
        updateNonTrainingtargetsAleapContingency: API_BASE_URL + '/non-training/resource/update/',
        deleteNonTrainingtargetsAleapContingency: API_BASE_URL + '/non-training/resource/delete/',
        getNonTrainingtargetsAleapPaymentsId: API_BASE_URL + '/non-training/all/resource/expenditures?nonTrainingActivityId=',
        saveNonTrainingtargetsAleapContingencyPayment: API_BASE_URL + '/non-training/non-training/expenditure/resource',
        updateNonTrainingtargetsAleapContingencyPayment: API_BASE_URL + '/non-training/resource-expenditure/update/',
        deleteNonTrainingtargetsAleapContingencyPayment: API_BASE_URL + '/non-training/resource/expenditure/delete/',
         updateNonTrainingtargetsTravel: API_BASE_URL + '/api/travel/',
        deleteNonTrainingtargetsTravel: API_BASE_URL + '/api/travel/',
        saveNonTrainingtargetsTravel: API_BASE_URL + '/api/travel/save',
        updateNonTrainingtargetsCandidate: API_BASE_URL + '/',
        deleteNonTrainingtargetsCandidate: API_BASE_URL + '/',
        saveNonTrainingtargetsCandidate: API_BASE_URL + '/save',
        getNonTrainingtargetsCandidate: API_BASE_URL + '/by-subactivity?subActivityId=',

        tihcl:{
            getCorpusList: API_BASE_URL + '/corpusDebitFinancing',
            getTihclData: API_BASE_URL + '/listing-on-nse/sub-activity/',
            savetihclData: API_BASE_URL + '/listing-on-nse/save',
            deletetihclData: API_BASE_URL + '/listing-on-nse/delete/',
        },
         nimsme:{
            getCorpusList: API_BASE_URL + '/corpusDebitFinancing',
            getdataMedia_doc: API_BASE_URL + '/central-data/content/subActivity/',
            savedataMedia_doc: API_BASE_URL + '/central-data/content/save',
            deletedataMedia_doc: API_BASE_URL + '/central-data/content/',
            updatedataMedia_doc: API_BASE_URL + '/central-data/content/',
             getdataVendor_doc: API_BASE_URL + '/vendors/get/',
            savedataVendor_doc: API_BASE_URL + '/vendors/save',
            deletedataVendor_doc: API_BASE_URL + '/vendors/',
            updatedataVendor_doc: API_BASE_URL + '/vendors/',
        },
        updateTechnologyAdoption: API_BASE_URL + '/wehub_sdg/update',
        saveTechnologyAdoption: API_BASE_URL + '/wehub_sdg/save',
        getTechnologyAdoption: API_BASE_URL + '/wehub_sdg/sub-activity/',
        deleteTechnologyAdoption: API_BASE_URL + '/wehub_sdg/',
       
    },
    progressMonitoring:{
        getTrainigAndNonTraining: API_BASE_URL + '/progress/monitoring/non-training-targets',
        getNonTrainingProgress: API_BASE_URL + '/progress/monitoring/training-targets',
        getTrainigTargetsAchievements: API_BASE_URL + '/training/targets-and-achievements/agency/',
        getNonTrainigTargetsAchievements: API_BASE_URL + '/non-training/targets-and-achievements/agency/',
    },
    captureOutcome:{
        getParticipantData: API_BASE_URL + '/getParticipantsByMobileNo/',
        getParticipantDataByMobile: API_BASE_URL + '/participants/search-by-mobile/',
        getOutcomelistData: API_BASE_URL + '/program/outcome/tables',
        getDynamicFormDataBasedOnOutCome: API_BASE_URL + '/program/outcome/details/',
        saveOutComes:API_BASE_URL + '/program/outcome/save/',
        getOutputProgressData:API_BASE_URL + '/get/outcome-targets/',
        viewOutcomelistData: API_BASE_URL + '/fetch/outcome-data',
    },
    callCenter:{
        getParticipantVerificationById:API_BASE_URL + `/program/participant-verification`,
        getQuestionById:API_BASE_URL + `/get/questions/subactivity/id/`,
        getDataByProgramVerificationId: API_BASE_URL + '/program/participant-verification/',
        add:API_BASE_URL + `/save/callcenter/verification/data`,
        getALLQuestion:API_BASE_URL + `/all/questions`,
        getVeriaficationStatus:API_BASE_URL + `/all/verification/status`,
        saveVeriaficationStatus:API_BASE_URL + `/save/callcenter/verification/data`,
        updateNotificationCCToAgency:API_BASE_URL + `/notifications/send/callcenter-to-agency`
    },
    Attendance:{
        getDeatails:API_BASE_URL +`/program/attendence/`,
        saveAttendance:API_BASE_URL +`/program/attendence`,
    },
    programFeedback:{
        updateFeedbackData:API_BASE_URL+'/new/program/feedback/update/',
        getFeedbackData:API_BASE_URL+'/new/program/feedback/id/',
        approvalFeedbackData:API_BASE_URL+'/jd-approvals/save',
    },
    rawMaterial:{
        getDeatails:API_BASE_URL +`/program/rawmaterial/`,
        saveAttendance:API_BASE_URL +`/program/rawmaterial`,
    },
    programExpenditure:{
        getItemByExpenses:API_BASE_URL +`/bulk/transactions/items?expenseId`,
        getBulkDataByExpensesItem:API_BASE_URL +`/bulk/transactions/lookup`,
        getHeadOfExpenditure:API_BASE_URL +`/expenses`,
        saveExpenditure:API_BASE_URL +`/program/expenditure/save`,
        savebulkExpenditure:API_BASE_URL +`/bulk/expenditure/save`,
        updatebulkExpenditure:API_BASE_URL +`/bulk/expenditure/update/`,
        savebulkByItemExpenditure:API_BASE_URL +`/bulk/transactions/save`,
        UpdatebulkByItemTranstion:API_BASE_URL +`/bulk/transactions/update/`,  
        getExpenditure:API_BASE_URL +`/program/expenditure`,
        getExpenditureByAgency:API_BASE_URL +`/program/expenditure/agency/`,
        getBulkExpenditure:API_BASE_URL +`/bulk/expenditure`,
        getBulkExpenditureByAgency:API_BASE_URL +`/bulk/expenditure/agency/`,
        getBulkExpenditureByProgramId:API_BASE_URL +`/bulk/transactions`,
        deleteExpenditure:API_BASE_URL +`/program/expenditure/delete/`,
        deleteTransation:API_BASE_URL +`/bulk/transactions/delete/`,
        UpdateExpenditure:API_BASE_URL +`/program/expenditure/update/`,
        deleteBulkExpenditure:API_BASE_URL +`/bulk/expenditure/delete/`,
        downloadExpeditureData:API_BASE_URL +`/export-program-expenditure`,
        saveRemarks:API_BASE_URL +`/save/remarks`,
        saveRemarksBulk:API_BASE_URL +`/save/remarks/transaction`
    },
    programSummary:{
        getProramData:API_BASE_URL +`/program/summary/`,
        getParticipantsBYProgram:API_BASE_URL +`/program/participants/dropdown/`,
    },
    programExecutions:{
        saveMediaCoverage:API_BASE_URL +`/program/execution/media-coverage`,
        saveProgramExecution:API_BASE_URL +`/program/execution/images`,
    },
    programMonitoring:{
        getProgramMonitoringById:API_BASE_URL +`/new/program/details/for/feedback/`,
        getProgramMonitoringByIdUpdated:API_BASE_URL +`/new/program/feedback/id/`,
        getProgramMonitoringByIdProgram:API_BASE_URL +`/new/program/feedback/`,
        // getProgramMonitoringById:API_BASE_URL +`/program/monitoring/`,
        saveProgramMonitoring:API_BASE_URL +`/new/program/feedback/save`,
        updateProgramMonitoring:API_BASE_URL +`/new/program/feedback/update/`,
    },
    collageCreation:{
        GET_ALL_IMAGES: API_BASE_URL+`/program/file/paths/`,
        GET_COLLAGE_IMAGES: API_BASE_URL+`/program/file/paths/status?fileType=COLLAGE`,
        UPLOAD_COLLAGE: API_BASE_URL+`/program/collage/images`,
        GET_AGENCIES: API_BASE_URL+`/agencies`,
        GET_PROGRAMS: API_BASE_URL+`/agency/programs/dropdown`,
    },
    questionsApis:{
        getAllQuestions: API_BASE_URL + '/all/questions',
        saveActivityQuestions: API_BASE_URL + '/save/subactivity/questions',
        saveQuestion: API_BASE_URL + '/save/question',
        getQuestionsById: API_BASE_URL + '/get/questions/subactivity/id/',
    },
    notificationDisplay:{
        getNotificationDisplayByAgency: API_BASE_URL + '/notifications/agency/remarks/',
        getNotificationDisplayByCallCenter: API_BASE_URL + '/notifications/callcenter/remarks/',
        getNotificationByAgency: API_BASE_URL + '/notifications/agency/',
        getNotificationByCallCenter: API_BASE_URL + '/notifications/callcenter/',
        getNotifications: API_BASE_URL + '/notifications/by-user',
        markAsRead: API_BASE_URL + '/notifications/mark-read',
        updateData: API_BASE_URL + '/notifications/status',
    },
    msmeQueaterly:{
        getMSMEByQuarter: API_BASE_URL + '/momsme/report/by-quarter',
        getlistOfIntervention: API_BASE_URL + '/momsme/interventions',
        getMSMEByMonth: API_BASE_URL + '/momsme/report/by-month',
        saveMonth: API_BASE_URL + '/momsme/submitted-save',
        getCuulativebyIntervention: API_BASE_URL + '/momsme/report/by-cumulative',
        pushToMoMSME: API_BASE_URL + '/momsme/push-to-momsme'
    },
    tickets: {
        getAllUser: API_BASE_URL + '/login/allusrs',
        save: API_BASE_URL + '/tickets',
        getAll: API_BASE_URL + '/tickets',
        getAllById: API_BASE_URL + '/tickets/',
        getDataByReportId: API_BASE_URL + '/tickets/report/',
        update: API_BASE_URL + '/tickets/',
        delete: API_BASE_URL + '/tickets/delete/',
         getAllAssineeId: API_BASE_URL + '/tickets/specific-users',
    }
}