import { get } from "jquery";
import { environment } from "src/environments/environment";

export const API_BASE_URL = environment.apiUrl;
export const APIS = {
    programCreation:{
        addprogram: API_BASE_URL + '/program/create',
        addSessions: API_BASE_URL + '/program/session/create',
        editSession: API_BASE_URL + '/program/session/update',
        addLocation: API_BASE_URL + '/location/save',
        getLocation: API_BASE_URL + '/agency/locations/',
        getProgramType: API_BASE_URL + '/program/types/agency/id/',
        getLocationByAgency: API_BASE_URL + '/agency/locationdetails',
        getResource: API_BASE_URL + '/agency/resources',
        addResource: API_BASE_URL + '/resource/save',
        getProgramsList: API_BASE_URL + '/programs',
        getProgramsListByAgency: API_BASE_URL + '/agency/programs/dropdown/',
        getProgramsListByAgencyStatus: API_BASE_URL + '/programs/status',
        getProgramsListByAgencyDetails: API_BASE_URL + '/agency/programs/',
        getProgramsListByAgencyByStatusDetails: API_BASE_URL + '/agency/programs/by/status/',
        getSingleProgramsList: API_BASE_URL + '/program/',
        getActivityList: API_BASE_URL + '/activities',
        getActivityListbyId: API_BASE_URL + '/activity/agency/',
        getSubActivityListByActivity: API_BASE_URL + '/activityById',
        getESDPProgram: API_BASE_URL + '/getESDPTraining',
        addESDPProgram: API_BASE_URL + '/SaveESDPTraining',
        updateProgram: API_BASE_URL + '/updateProgram',
        deleteSession: API_BASE_URL + '/program/session/delete',
        deleteProgram: API_BASE_URL + '/program/delete/',
        getProgramsListBySession: API_BASE_URL + '/programs/status/',
        updateSessionByStatus: API_BASE_URL + '/programs/status/',
        programSummary: API_BASE_URL + '/programs/status/summary/',
        sessionFilesDelete: API_BASE_URL + '/program-session-files/', 
        uploadProgram: API_BASE_URL + '/program/import', 
        downloadProgramsData: API_BASE_URL + '/program/pdf/',
        downloadResourceData: API_BASE_URL + '/resource/excel/',
        downloadSessionsData: API_BASE_URL + '/program/session/pdf/',
        updateOverDue: API_BASE_URL + '/',
        getProgramsListByDistrictDetails: API_BASE_URL + '/agency/programs/district/',
        // get: API_BASE_URL + '/program/get',
        // update: API_BASE_URL + '/program/update',
        // delete: API_BASE_URL + '/program/delete',
    },
    physicalTagets:{
        getTargets: API_BASE_URL + '/targets/physical/agency/',
        saveTargets: API_BASE_URL + '/targets/physical/save',
        updateTargets: API_BASE_URL + '/targets/physical/update/',
        deleteTargets: API_BASE_URL + '/targets/physical/',
        getTargetById: API_BASE_URL + '/targets/physical/',
    },
    FinancialTagets:{
        getTargets: API_BASE_URL + '/api/outcome-targets?',
        saveTargets: API_BASE_URL + '/targets/physical/save',
        updateTargets: API_BASE_URL + '/targets/physical/update/',
        deleteTargets: API_BASE_URL + '/targets/physical/',
        getTargetById: API_BASE_URL + '/targets/physical/',
    },
    participantdata:{
        add: API_BASE_URL + '/participant/save',
        update: API_BASE_URL + '/updateParticipant',
        getDataByProgramId: API_BASE_URL + '/program/participants/dropdown/',
        getDataByProgramBYDeatisl: API_BASE_URL + '/program/participants/',
        getDataUploadedByProgramBYDeatisl: API_BASE_URL + '/participants/temp/',
        saveOrgnization: API_BASE_URL + '/organization/save',
        getOrgnizationData: API_BASE_URL + '/organization/list',
        getParticipantList: API_BASE_URL + '/participants',
        getParticipantListByAgency: API_BASE_URL + '/agency/participants/',
        getParticipantDetailsById: API_BASE_URL + '/getParticipantById/',
        uploadParticipant: API_BASE_URL + '/upload',
        uploadParticipantData: API_BASE_URL + '/participants/import',
        downloadParticipantData: API_BASE_URL + '/program/participant/pdf/',
        downloadParticipantTempData: API_BASE_URL + '/ParticipantTemp/excel/sheets/',
        migrateApi: API_BASE_URL + '/participants/temp/migrate',
        deleteTempParticipant: API_BASE_URL + '/participants/temp/',
        updateTempParticipant: API_BASE_URL + '/participants/temp/',
    },
    counsellerData:{
        add: API_BASE_URL + '/saveCounsellor',
        getData: API_BASE_URL + '/getAllCounsellors',
    },
    userRegistration:{
        add: API_BASE_URL + '/auth/register',
        addAgent: API_BASE_URL + '/auth/register',
        editProfile: API_BASE_URL + '/login/user/update',
        getUserById: API_BASE_URL + '/login/user',        
    },
    masterList: {
        changePassword:API_BASE_URL+'/login/change-password',
        agencyList: API_BASE_URL + '/agencies',
        locationList: API_BASE_URL + '/locations',
        getUserList: API_BASE_URL + '/login/allusrs',
        getresources: API_BASE_URL + '/resources',
        getDistricts: API_BASE_URL + '/getAllDistricts',
        getSectors: API_BASE_URL + '/getallsectors',
        getMandal: API_BASE_URL + '/getAllmandalsOfDistrictsById/',
        getMandalName: API_BASE_URL + '/getAllmandalsOfDistrictsByName/',
    },
    trainingtargets:{
        getTrainingtargets: API_BASE_URL + '/targets/financial/year/summary',

    },
    nontrainingtargets:{
        getBudgetHeadList: API_BASE_URL + '/progress/monitoring/get/activities/',
        getResourceList: API_BASE_URL + '/non-training/resources/non-training-activity?nonTrainingActivityId=',
        updateTarets: API_BASE_URL + '/progress/monitoring/non-training-achievement/',
        getNonTrainingtargets: API_BASE_URL + '/progress/monitoring/non-training/physical/financial/{activityId}?activityId=',
        saveNonTrainingtargetsAleapPriliminary: API_BASE_URL + '/non-training',
        updateNonTrainingtargetsAleapPriliminary: API_BASE_URL + '/non-training/update/',
        deleteNonTrainingtargetsAleapPriliminary: API_BASE_URL + '/non-training/delete/',
        getNonTrainingtargetsAleapPriliminaryById: API_BASE_URL + '/non-training/all/expenditures?nonTrainingActivityId=',
        getNonTrainingtargetsAleapContingencyId: API_BASE_URL + '/non-training/all/resources?nonTrainingActivityId=',
        saveNonTrainingtargetsAleapContingency: API_BASE_URL + '/non-training/resource',
        updateNonTrainingtargetsAleapContingency: API_BASE_URL + '/non-training/resource/update/',
        deleteNonTrainingtargetsAleapContingency: API_BASE_URL + '/non-training/resource/delete/',
        getNonTrainingtargetsAleapPaymentsId: API_BASE_URL + '/non-training/all/resource/expenditures?nonTrainingActivityId=',
        saveNonTrainingtargetsAleapContingencyPayment: API_BASE_URL + '/non-training/non-training/expenditure/resource',
        updateNonTrainingtargetsAleapContingencyPayment: API_BASE_URL + '/non-training/resource-expenditure/update/',
        deleteNonTrainingtargetsAleapContingencyPayment: API_BASE_URL + '/non-training/resource/expenditure/delete/',
       
    },
    progressMonitoring:{
        getTrainigAndNonTraining: API_BASE_URL + '/progress/monitoring',
        getTrainigTargetsAchievements: API_BASE_URL + '/training/targets-and-achievements/agency/',
        getNonTrainigTargetsAchievements: API_BASE_URL + '/non-training/targets-and-achievements/agency/',
    },
    captureOutcome:{
        getParticipantData: API_BASE_URL + '/getParticipantsByMobileNo/',
        getOutcomelistData: API_BASE_URL + '/program/outcome/tables',
        getDynamicFormDataBasedOnOutCome: API_BASE_URL + '/program/outcome/details/',
        saveOutComes:API_BASE_URL + '/program/outcome/save/',
    },
    callCenter:{
        getParticipantVerificationById:API_BASE_URL + `/program/participant-verification`,
        getQuestionById:API_BASE_URL + `/get/questions/subactivity/id/`,
        getDataByProgramVerificationId: API_BASE_URL + '/program/participant-verification/',
        add:API_BASE_URL + `/save/callcenter/verification/data`,
        getALLQuestion:API_BASE_URL + `/all/questions`,
        getVeriaficationStatus:API_BASE_URL + `/all/verification/status`,
        saveVeriaficationStatus:API_BASE_URL + `/save/callcenter/verification/data`
    },
    Attendance:{
        getDeatails:API_BASE_URL +`/program/attendence/`,
        saveAttendance:API_BASE_URL +`/program/attendence`,
    },
    rawMaterial:{
        getDeatails:API_BASE_URL +`/program/rawmaterial/`,
        saveAttendance:API_BASE_URL +`/program/rawmaterial`,
    },
    programExpenditure:{
        getItemByExpenses:API_BASE_URL +`/bulk/transactions/items?expenseId`,
        getBulkDataByExpensesItem:API_BASE_URL +`/bulk/transactions/lookup`,
        getHeadOfExpenditure:API_BASE_URL +`/expenses`,
        saveExpenditure:API_BASE_URL +`/program/expenditure/save`,
        savebulkExpenditure:API_BASE_URL +`/bulk/expenditure/save`,
        updatebulkExpenditure:API_BASE_URL +`/bulk/expenditure/update/`,
        savebulkByItemExpenditure:API_BASE_URL +`/bulk/transactions/save`,
        UpdatebulkByItemTranstion:API_BASE_URL +`/bulk/transactions/update/`,  
        getExpenditure:API_BASE_URL +`/program/expenditure`,
        getExpenditureByAgency:API_BASE_URL +`/program/expenditure/agency/`,
        getBulkExpenditure:API_BASE_URL +`/bulk/expenditure`,
        getBulkExpenditureByAgency:API_BASE_URL +`/bulk/expenditure/agency/`,
        getBulkExpenditureByProgramId:API_BASE_URL +`/bulk/transactions`,
        deleteExpenditure:API_BASE_URL +`/program/expenditure/delete/`,
        deleteTransation:API_BASE_URL +`/bulk/transactions/delete/`,
        UpdateExpenditure:API_BASE_URL +`/program/expenditure/update/`,
        deleteBulkExpenditure:API_BASE_URL +`/bulk/expenditure/delete/`,
        downloadExpeditureData:API_BASE_URL +`/export-program-expenditure`,
        saveRemarks:API_BASE_URL +`/save/remarks`,
        saveRemarksBulk:API_BASE_URL +`/save/remarks/transaction`
    },
    programSummary:{
        getProramData:API_BASE_URL +`/program/summary/`,
        getParticipantsBYProgram:API_BASE_URL +`/program/participants/dropdown/`,
    },
    programExecutions:{
        saveMediaCoverage:API_BASE_URL +`/program/execution/media-coverage`,
        saveProgramExecution:API_BASE_URL +`/program/execution/images`,
    },
    programMonitoring:{
        getProgramMonitoringById:API_BASE_URL +`/new/program/details/for/feedback/`,
        getProgramMonitoringByIdUpdated:API_BASE_URL +`/new/program/feedback/id/`,
        getProgramMonitoringByIdProgram:API_BASE_URL +`/new/program/feedback/`,
        // getProgramMonitoringById:API_BASE_URL +`/program/monitoring/`,
        saveProgramMonitoring:API_BASE_URL +`/new/program/feedback/save`,
        updateProgramMonitoring:API_BASE_URL +`/new/program/feedback/update/`,
    },
    collageCreation:{
        GET_ALL_IMAGES: API_BASE_URL+`/program/file/paths/`,
        GET_COLLAGE_IMAGES: API_BASE_URL+`/program/file/paths/status?fileType=COLLAGE`,
        UPLOAD_COLLAGE: API_BASE_URL+`/program/collage/images`,
        GET_AGENCIES: API_BASE_URL+`/agencies`,
        GET_PROGRAMS: API_BASE_URL+`/agency/programs/dropdown`,
    },
}